development:
  cloud_name: "dkqb36vdl"
  api_key: "993745872148697"
  api_secret: "CJNDVHKZMO5aILaDQy1eAEmPHbU"
  secure: true

production:
  cloud_name: "dkqb36vdl"
  api_key: "993745872148697"
  api_secret: "CJNDVHKZMO5aILaDQy1eAEmPHbU"
  secure:true
